### PR TITLE
Feature: RLZ-2834 business valuation component

### PR DESCRIPTION
**Pull request by mashuoyi111**

### CODE REVIEW

**Review by spersico — DISMISSED** [review]
Okay, I'm just reviewing the code, I don't have a clue about the calculations, specially all about what's in the `business-valuations.utils.tsx` file

But I found some things to complain about:
image

I think the responsive version needs some work

For the 600px version:
image

And lastly, the error and loading states don't look like the Figma (it's supposed to be wrapped in the component border and be centered and whatnot)
Screenshot 2023-04-27 at 17 06 47

**Comment by spersico** [comment]
By the way, I used QA1, with customer "CST-e4680a1a-f737-4d09-afe6-a16572b242ab" and business "TestBusinessQbo" with this filters to show the Infinity value
image

**Comment by mashuoyi111** [comment]
Hi @spersico styling fixed accordingly. Please test again with full width for accurate layout. I will ask our team what to do with inifinity values
https://user-images.githubusercontent.com/19851927/235005729-d1239667-d110-4ca3-b98e-b9f782932ffa.mov

**Comment by mashuoyi111** [comment]
Screenshot 2023-04-27 at 3 50 48 PM

**Comment by spersico** [comment]
image
The issue with not having wrapper boxes is... sort of fixed, I found new issues around it though

**Comment by spersico** [comment]
At 900px it doesn't look like the figma
Screenshot 2023-04-28 at 11 29 18

Neither at 600px
image

The distribution of the columns is not being done while mantaining the correct spacing between elements, so when the row breaks into 2, the right border of each element breask and the spacing stops behaving.
My understanding of this, is that even though the element is big, we need to support to up to 600px of width for it, and it should look fine on every resolution from 600 to full width.

**Comment by mashuoyi111** [comment]
@spersico the issues you mentioned are fixed now with new layout

**Comment by cfenos** [comment]
I'm going to approve, but if I could make a nit picky remark. Can we make the drop down options in the example alphabetized @maxmarailz

**Review by cfenos — APPROVED** [review]

**Pull request merged**
